root = "."
tmp_dir = "build"

[build]
bin = "./build/memos.exe --mode dev"
cmd = "go build -o ./build/memos.exe ./bin/memos/main.go"
delay = 1000
exclude_dir = ["web", "build"]
include_ext = ["go", "mod", "sum"]
exclude_file = []
exclude_regex = []
exclude_unchanged = true
follow_symlink = false
send_interrupt = true
kill_delay = 2000
stop_on_error = true
